const BillingData = [
  {
    appointmentID: "BC001",
    customerName: "Rahul Sharma",
    doctorName: "Dr. Amit Verma",
    dateTime: "19/11/2024 10:30AM",
    category: "General Checkup",
    status: "Scheduled",
    staffAssigned: "Nurse Riya",
    paymentStatus: "Paid",
    amount: 500,
    contactInfo: "+91 9876543210",
  },
  {
    appointmentID: "BC002",
    customerName: "Neha Gupta",
    doctorName: "Dr. Sneha Kapoor",
    dateTime: "19/11/2024 12:00PM",
    category: "Dermatology",
    status: "Completed",
    staffAssigned: "Nurse Meera",
    paymentStatus: "Pending",
    amount: 1500,
    contactInfo: "+91 8765432109",
  },
  {
    appointmentID: "BC003",
    customerName: "Amit Singh",
    doctorName: "Dr. Rajeev Malhotra",
    dateTime: "20/11/2024 9:00AM",
    category: "Orthopedics",
    status: "Scheduled",
    staffAssigned: "Assistant Ravi",
    paymentStatus: "Paid",
    amount: 2000,
    contactInfo: "+91 7654321098",
  },
  {
    appointmentID: "BC004",
    customerName: "Priya Verma",
    doctorName: "Dr. Sneha Kapoor",
    dateTime: "20/11/2024 10:00AM",
    category: "Pediatrics",
    status: "Canceled",
    staffAssigned: "Nurse Riya",
    paymentStatus: "Refunded",
    amount: 1000,
    contactInfo: "+91 6543210987",
  },
  {
    appointmentID: "BC005",
    customerName: "Vikas Mehta",
    doctorName: "Dr. Rajeev Malhotra",
    dateTime: "20/11/2024 11:00AM",
    category: "Cardiology",
    status: "Completed",
    staffAssigned: "Assistant Ravi",
    paymentStatus: "Paid",
    amount: 3000,
    contactInfo: "+91 5432109876",
  },
  {
    appointmentID: "BC006",
    customerName: "Anjali Sinha",
    doctorName: "Dr. Amit Verma",
    dateTime: "21/11/2024 9:30AM",
    category: "Radiology",
    status: "Scheduled",
    staffAssigned: "Nurse Meera",
    paymentStatus: "Pending",
    amount: 2500,
    contactInfo: "+91 4321098765",
  },
  {
    appointmentID: "BC007",
    customerName: "Suresh Kumar",
    doctorName: "Dr. Sneha Kapoor",
    dateTime: "21/11/2024 1:00PM",
    category: "Neurology",
    status: "Scheduled",
    staffAssigned: "Nurse Riya",
    paymentStatus: "Paid",
    amount: 4000,
    contactInfo: "+91 3210987654",
  },
  {
    appointmentID: "BC008",
    customerName: "Rohit Sharma",
    doctorName: "Dr. Rajeev Malhotra",
    dateTime: "21/11/2024 2:30PM",
    category: "Orthopedics",
    status: "Rescheduled",
    staffAssigned: "Assistant Ravi",
    paymentStatus: "Pending",
    amount: 2200,
    contactInfo: "+91 2109876543",
  },
  {
    appointmentID: "BC009",
    customerName: "Pooja Malhotra",
    doctorName: "Dr. Amit Verma",
    dateTime: "22/11/2024 10:00AM",
    category: "General Checkup",
    status: "Scheduled",
    staffAssigned: "Nurse Meera",
    paymentStatus: "Paid",
    amount: 600,
    contactInfo: "+91 1098765432",
  },
  {
    appointmentID: "BC010",
    customerName: "Naina Gupta",
    doctorName: "Dr. Sneha Kapoor",
    dateTime: "22/11/2024 11:30AM",
    category: "Dermatology",
    status: "Completed",
    staffAssigned: "Nurse Riya",
    paymentStatus: "Paid",
    amount: 1700,
    contactInfo: "+91 9876543211",
  },
];

export default BillingData;
