export const BillingData = [
    {
      bookingId: "10054",
      appointmentId: "20015",
      patientName: "XYZ",
      referredDoctor: "XYZ",
      testType: ["Blood Test", "CT"],
      department: "Pathology",
      status: "Completed",
      amountPaid: "Rs. 5000/-",
      dateTime: "2024-11-21 10:00 AM",
    },
    {
      bookingId: "10054",
      appointmentId: "20015",
      patientName: "XYZ",
      referredDoctor: "XYZ",
      testType: ["Blood Test"],
      department: "Radiology",
      status: "Completed",
      amountPaid: "Rs. 5000/-",
      dateTime: "2024-11-21 10:00 AM",
    },
    {
      bookingId: "10054",
      appointmentId: "20015",
      patientName: "XYZ",
      referredDoctor: "XYZ",
      testType: ["Blood Test"],
      department: "Pathology",
      status: "Completed",
      amountPaid: "Rs. 5000/-",
      dateTime: "2024-11-21 10:00 AM",
    },
    {
      bookingId: "10055",
      appointmentId: "20016",
      patientName: "ABC",
      referredDoctor: "ABC",
      testType: ["Blood Test", "MRI"],
      department: "Pathology",
      status: "Completed",
      amountPaid: "Rs. 6000/-",
      dateTime: "2024-11-21 12:00 PM",
    },
    {
      bookingId: "10056",
      appointmentId: "20017",
      patientName: "DEF",
      referredDoctor: "DEF",
      testType: ["Blood Test"],
      department: "Pathology",
      status: "Completed",
      amountPaid: "Rs. 4500/-",
      dateTime: "2024-11-21 02:00 PM",
    },
    // Add more entries as required
  ];
  
  export default BillingData;